// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.4
// source: sayhello.proto

package sayhello

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Sayhello_Ping_FullMethodName = "/sayhello.Sayhello/Ping"
)

// SayhelloClient is the client API for Sayhello service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SayhelloClient interface {
	Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type sayhelloClient struct {
	cc grpc.ClientConnInterface
}

func NewSayhelloClient(cc grpc.ClientConnInterface) SayhelloClient {
	return &sayhelloClient{cc}
}

func (c *sayhelloClient) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, Sayhello_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SayhelloServer is the server API for Sayhello service.
// All implementations must embed UnimplementedSayhelloServer
// for forward compatibility.
type SayhelloServer interface {
	Ping(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedSayhelloServer()
}

// UnimplementedSayhelloServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSayhelloServer struct{}

func (UnimplementedSayhelloServer) Ping(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedSayhelloServer) mustEmbedUnimplementedSayhelloServer() {}
func (UnimplementedSayhelloServer) testEmbeddedByValue()                  {}

// UnsafeSayhelloServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SayhelloServer will
// result in compilation errors.
type UnsafeSayhelloServer interface {
	mustEmbedUnimplementedSayhelloServer()
}

func RegisterSayhelloServer(s grpc.ServiceRegistrar, srv SayhelloServer) {
	// If the following call pancis, it indicates UnimplementedSayhelloServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Sayhello_ServiceDesc, srv)
}

func _Sayhello_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SayhelloServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sayhello_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SayhelloServer).Ping(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// Sayhello_ServiceDesc is the grpc.ServiceDesc for Sayhello service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Sayhello_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sayhello.Sayhello",
	HandlerType: (*SayhelloServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Sayhello_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sayhello.proto",
}
