// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1
// Source: sayhello.proto

package server

import (
	"context"

	"iknow/micros/sayhello/internal/logic"
	"iknow/micros/sayhello/internal/svc"
	"iknow/micros/sayhello/sayhello"
)

type SayhelloServer struct {
	svcCtx *svc.ServiceContext
	sayhello.UnimplementedSayhelloServer
}

func NewSayhelloServer(svcCtx *svc.ServiceContext) *SayhelloServer {
	return &SayhelloServer{
		svcCtx: svcCtx,
	}
}

func (s *SayhelloServer) Ping(ctx context.Context, in *sayhello.Request) (*sayhello.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
