// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1
// Source: sayhello.proto

package sayhelloclient

import (
	"context"

	"iknow/micros/sayhello/sayhello"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Request  = sayhello.Request
	Response = sayhello.Response

	Sayhello interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	}

	defaultSayhello struct {
		cli zrpc.Client
	}
)

func NewSayhello(cli zrpc.Client) Sayhello {
	return &defaultSayhello{
		cli: cli,
	}
}

func (m *defaultSayhello) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := sayhello.NewSayhelloClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}
