{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "sayhello-api.fullname" . }}-endpoints-reader
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sayhello-api.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "sayhello-api.fullname" . }}-endpoints-reader
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sayhello-api.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "sayhello-api.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "sayhello-api.fullname" . }}-endpoints-reader
  apiGroup: rbac.authorization.k8s.io
{{- end }}
